# Application Name
spring.application.name=Clicks-App

# Server Port
server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.streams.bootstrap-servers=localhost:9092
spring.kafka.streams.application-id=click-stream-app

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Configuration
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.LongDeserializer

# Kafka Consumer Group Configuration (Important for Kafka Stream)
spring.kafka.consumer.group-id=clicks-consumer-group

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
